# Generated by Django 4.2 on 2024-02-20 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NLPConfig',
            fields=[
                ('id', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_column='key', max_length=32)),
                ('value', models.CharField(db_column='value', max_length=32)),
            ],
            options={
                'db_table': 'config',
            },
        ),
        migrations.CreateModel(
            name='NLPEventModel',
            fields=[
                ('id', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('desc', models.TextField(db_column='desc', null=True)),
            ],
            options={
                'db_table': 'event_model',
            },
        ),
        migrations.CreateModel(
            name='NLPEvents',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('evnet_name', models.CharField(db_column='event_name', max_length=32)),
                ('desc', models.TextField(db_column='desc', null=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='NLPModels',
            fields=[
                ('id', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=64)),
                ('type', models.CharField(choices=[('S', 'Service'), ('T', 'Training')], db_column='type', max_length=1)),
                ('path', models.CharField(db_column='path', max_length=1024)),
                ('base', models.CharField(db_column='base', max_length=1024)),
                ('version', models.CharField(db_column='version', max_length=32)),
                ('desc', models.TextField(db_column='desc', null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, db_column='last_modified')),
                ('token_base', models.CharField(db_column='token_base', max_length=200)),
                ('token_path', models.CharField(db_column='token_path', max_length=200)),
                ('train_prefix', models.CharField(db_column='train_prefix', max_length=200)),
            ],
            options={
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='NLPTrainData',
            fields=[
                ('id', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('data', models.BinaryField(db_column='data')),
                ('last_modified', models.DateTimeField(auto_now=True, db_column='last_modified')),
            ],
            options={
                'db_table': 'train_data',
            },
        ),
        migrations.CreateModel(
            name='NLPTrainReservation',
            fields=[
                ('id', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now=True, db_column='start_time')),
                ('enable', models.BooleanField(db_column='enable', default=False)),
                ('status', models.CharField(choices=[('N', 'Not started'), ('S', 'Started'), ('P', 'Paused'), ('C', 'Completed'), ('E', 'Error')], db_column='status', max_length=1)),
                ('event_model', models.ForeignKey(db_column='event_model_id', on_delete=django.db.models.deletion.CASCADE, to='nlp.nlpeventmodel')),
                ('train_data', models.ForeignKey(db_column='train_data_id', on_delete=django.db.models.deletion.CASCADE, to='nlp.nlptraindata')),
            ],
            options={
                'db_table': 'train_reservation',
            },
        ),
        migrations.CreateModel(
            name='NLPInputTexts',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('input_text', models.TextField(db_column='input_text')),
                ('desc', models.TextField(db_column='desc', null=True)),
                ('enable', models.BooleanField(db_column='enable', default=False)),
                ('last_modified', models.DateTimeField(auto_now=True, db_column='last_modified')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='nlp.nlpevents')),
            ],
            options={
                'db_table': 'input_texts',
            },
        ),
        migrations.AddField(
            model_name='nlpeventmodel',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='nlp.nlpevents'),
        ),
        migrations.AddField(
            model_name='nlpeventmodel',
            name='model',
            field=models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, to='nlp.nlpmodels'),
        ),
        migrations.CreateModel(
            name='NLPCacheTexts',
            fields=[
                ('id', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('cache_text', models.TextField(db_column='cache_text')),
                ('enable', models.BooleanField(db_column='enable', default=False)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='nlp.nlpevents')),
            ],
            options={
                'db_table': 'cache_texts',
            },
        ),
    ]
