services:
  db:
    image: postgres:15
    # volumes:
    #   - ./db:/var/lib/postgresql/data
    env_file:
      - ./config/postgres/.env-dev
    ports:
      - 5432:5432
  nlp_db:
    image: postgres:15
    # volumes:
    #   - ./db:/var/lib/postgresql/data
    env_file:
      - ./config/postgres/.env-nlp-dev
    ports:
      - 5433:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 8000:8000
    env_file:
      - ./config/django/.env-dev
    depends_on:
      - db
      - nlp_db