services:
  db:
    image: postgres:14
    env_file:
      - ./config/postgres/.env-dev
    ports:
      - 5432:5432
  web:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./config/django/.env
    depends_on:
      - db