# Generated by Django 4.2 on 2024-02-20 03:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEventType',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(100)])),
            ],
            options={
                'db_table': 'custom_event_type',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
            ],
            options={
                'db_table': 'event_type',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('date', models.DateField(null=True)),
                ('repeat', models.IntegerField(null=True)),
                ('custom_event_type', models.ForeignKey(db_column='custom_event_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='event.customeventtype')),
                ('event_type', models.ForeignKey(db_column='event_type', on_delete=django.db.models.deletion.DO_NOTHING, to='event.eventtype')),
                ('friend', models.ForeignKey(db_column='friend', null=True, on_delete=django.db.models.deletion.CASCADE, to='friend.friend')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
