# Generated by Django 4.2 on 2024-02-20 03:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='\n            Phone number must be entered in the one of the following formats:\n            010-7890-1234\n            01078901234\n            027891234\n            02-789-1234\n            02 789 1234\n            02 7890 1234\n            02-7890-1234\n            032-789-1234\n            032-7890-1234\n            03278901234\n        ', regex='^\\d{2,3}[-\\s]\\d{3,4}[-\\s]\\d{4}$')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('birthday', models.DateField(null=True)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friend',
            },
        ),
    ]
