# Generated by Django 4.2 on 2024-02-20 03:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='\n            Phone number must be entered in the one of the following formats:\n            010-7890-1234\n            01078901234\n            027891234\n            02-789-1234\n            02 789 1234\n            02 7890 1234\n            02-7890-1234\n            032-789-1234\n            032-7890-1234\n            03278901234\n        ', regex='^\\d{2,3}[-\\s]\\d{3,4}[-\\s]\\d{4}$')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('kakao_id', models.CharField(editable=False, max_length=250, unique=True, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('kakao_nickname', models.CharField(max_length=250, null=True, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('profile_thumbnail', models.SlugField(max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('email', models.EmailField(max_length=250, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('kakao_refresh_token', models.CharField(max_length=500, unique=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('username', models.CharField(default='', max_length=250, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_type', models.CharField(choices=[('i', 'login'), ('o', 'logout')], default='o', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_log',
            },
        ),
    ]
